server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hardcore_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    com.hardcore.accounting: debug