server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hardcore_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.hardcore.accounting: debug